[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/models/*"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

# Ensure proper MIME types for 3D models
[[headers]]
  for = "/*.gltf"
  [headers.values]
    Content-Type = "model/gltf+json"

# Make sure the models directory is copied to dist during build
[build.processing]
  skip_processing = false